### ISSUE TITLE
Allow generating multiple formats

### ISSUE THREAD

**Issue by Rush** [dazuaz/responsive-loader#117]
When source is a png, it might be useful to generate multiple formats:

formats: [ "jpg", "webp"]

**Comment by dazuaz** [comment]
Hi @Rush,
Thanks for your suggestion,

The recommended way right now is to import/require once for each format you need,

I do not think it is worth the added complexity of handling different formats in one request, but maybe there is a use case that would make it worth,

Happy to hear suggestions.

**Comment by Rush** [comment]
@dazuaz for me it would be a hard requirement as I am exposing other formats on Nginx level. If content type supports webp, the server picks up webp instead of jpg/png

**Comment by michellocana** [comment]
I've stumble upon the same problem in the project i'm working on, where i want to use the original image formats (jpg/png) but also want to use webp/avif when the browser supports it. Manually importing different formats is not an option in my case because we have hundreds of images all across the project.

Maybe we could create a config like `extraFormats`, where we keep the original file format, but also generate different image formats, so we can always use the best image format available on the browser.

Webpack config example: 
```js
{
  test: /\.(jpe?g|png|webp)$/i,
  use: [
    {
      loader: "responsive-loader",
      options: {
        adapter: require("responsive-loader/sharp"),
        extraFormats: ["webp", "avif"],
        name: "[name].[ext]",
      },
    },
  ],
}
```

Output:
```json
{
  "src": "image.png",
  "srcSet": "image.png 1366w",
  "width": 1366,
  "height": 536,
  "images": [
    {
      "path": "image.png",
      "width": 1366,
      "height": 536
    }
  ],
  "extraFormats": [
    {
      "format": "webp",
      "src": "image.webp",
      "srcSet": "image.webp 1366w",
      "width": 1366,
      "height": 536,
      "images": [
        {
          "path": "image.webp",
          "width": 1366,
          "height": 536
        }
      ]
    },
    {
      "format": "avif",
      "src": "image.avif",
      "srcSet": "image.avif 1366w",
      "width": 1366,
      "height": 536,
      "images": [
        {
          "path": "image.avif",
          "width": 1366,
          "height": 536
        }
      ]
    }
  ]
}
```

Let me know if that makes sense, i can try to help with the implementation if it does :)
