### ISSUE TITLE
Can we just use percent instead of width or size?

### ISSUE THREAD

**Issue by matiniamirhossein** [dazuaz/responsive-loader#46]
Hello,
I'm having a question.
Can we just use percent instead of width or size?

**Comment by herrstucki** [comment]
Not at the moment. Maybe the [min, max, and steps option](https://github.com/herrstucki/responsive-loader#options) would work for that? But I don't really see the point of specifying something like `50%` since you'd generally want to control the output size precisely and not have it depend on an arbitrary input size.

**Comment by matiniamirhossein** [comment]
@herrstucki Thanks but with that I meant I generate an 8x image and serve it multipld times like 1x 2x 4x
